#============== BASE ==============#
baseURL           = 'https://masputrawae.github.io/'
languageCode      = "id"
title             = "My Notes"
enableEmoji       = true
buildFuture = true

#============== PARAMS ==============#
[params]
  author        = "Putra Jaya"
  description   = "Catatan-catatan pribadi yang mungkin hanya berguna untuk saya sendiri, atau mungkin alien di masa depan, siapa tahu?"
  logo          = "https://masputrawae.github.io/logo/logo.png"
  image         = "https://masputrawae.github.io/logo/logo.png"
  twitter       = "@Masputrawae"
  tagline       = ["A UI/UX Designer", "A Comedian", "A Learner"]

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
